name: Snowballz
main: com.nohupgaming.minecraft.Snowballz
version: 1.4
description: Snowballs that hit blocks now have an affect
author: Nohup
changelog:
  - v1.3  Added permissions support
  - v1.2  Bug-fix for block above
  - v1.1  Added properties support
  - v1.0  Initial release